# Generated by Django 4.1 on 2023-04-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("REST", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filtro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idUsuario", models.IntegerField()),
            ],
        ),
    ]
